#!/usr/bin/env python
# Project
from dfreduce.log import logger
from dfreduce import utils, cli
start_time = utils.timer()


###############################################################################
# Parse command-line arguments
###############################################################################
extra_args = {'skip-add-night': {'action': 'store_true'},
              'skip-check-lights': {'action': 'store_true'}}
args = utils.default_script_args(extra_args=extra_args)
dates = utils.parse_dates_to_list(args.dates, args.dates_fn)
config = utils.load_config(args.config_fn)


###############################################################################
# Step 0: Add night(s) to database
###############################################################################
if args.skip_add_night:
    logger.warning('SKIPPING add_night')
else:
    cli.add_night(args)


###############################################################################
# Step 1: Check quality of darks
###############################################################################
cli.check_darks(args)


###############################################################################
# Step 2: Create master darks and update the databases
###############################################################################
cli.create_master_darks(args)
cli.find_master_darks(args)


###############################################################################
# Step 3: Check quality of flats
###############################################################################
cli.check_flats(args)


###############################################################################
# Step 4: Create master flats and update the databases
###############################################################################
cli.create_master_flats(args)
cli.find_master_flats(args)


###############################################################################
# Step 5: Assess the quality of lights
###############################################################################
if args.skip_check_lights:
    logger.warning('SKIPPING check_lights')
else:
    cli.check_lights(args)


###############################################################################
# Job complete!
###############################################################################
utils.timer(start_time, 'Night Reduction')
